eureka:
  instance:
    ip-address: 127.0.0.1  
    hostname: localhost 
    prefer-ip-address: true 
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
server:
  port: 8888

spring:
  cloud:
    gateway:
        routes:
          - id: FORECAST-SERVICE
            uri: lb://forecast-service
            predicates:
              - Path=/forecast/**
            filters:
              - Authentication

          - id: WEATHER-SERVICE
            uri: lb://weather-service
            predicates:
              - Path=/weather/**
            filters:
              - Authentication

          - id: identity-service
            uri: lb://identity-service
            predicates:
              - Path=/auth/**
            filters:
              - SetRequestHeader=X-Request-Red, Blue
 application:
   name: API-GATEWAY


jwt:
  secret: ${JWT_SECRETS}
