server:
 port: 8082
  
eureka:
  instance:
    ip-address: 127.0.0.1  
    hostname: localhost 
    prefer-ip-address: true 
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    
spring:
  application:
    name: FORECAST-SERVICE
  datasource:
    url: jdbc:h2:mem:forecast_db
    username: root
    password: root
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: mapping,bus-refresh,bus-env,health,circuitbreakerevents
  endpoints:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
      
resilience4j:
  circuitbreaker:
    circuit-breaker-aspect-order: 1
    instances:
      book-service:
        failure-rate-threshold: 50
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        sliding-window-type: COUNT_BASED
        sliding-window-size: 2
        minimum-number-of-calls: 1
        permitted-number-of-calls-in-half-open-state: 3
        registerHealthIndicator: true
        event-consumer-buffer-size: 10
  retry:
    retry-aspect-order: 2
    instances:
      weather-service:
        max-attempts: 10
        wait-duration: 5000
